.\" -*-nroff-*-
.\"
.\" Copyright (C) 2012
.\" Martin Lambers <martin.lambers@uni-siegen.de>
.\"
.\" Copying and distribution of this file, with or without modification, are
.\" permitted in any medium without royalty provided the copyright notice and this
.\" notice are preserved. This file is offered as-is, without any warranty.
.TH ecmdb 1 2012-08
.SH NAME
ecmdb - create and manage ECM databases.
.SH DESCRIPTION
The \fBecmdb\fP tool provides a set of commands that create and manage ECM databases.
.SH USAGE
Use \fBecmdb help\fP to get a list of available commands, and
\fBecmdb help cmd\fP to get help for command \fBcmd\fP.
(Alternatively, you can use \fBecmdb --help\fP and \fBecmdb cmd --help\fP.)
.br
The full documentation is available in texinfo format.
.SH AUTHORS
Martin Lambers
